package quality

import("errors";"testing";"time";"go-base/internal/domain")

func sample(now time.Time)Sample{return Sample{ID:"sample-1",TenantID:"tenant-1",ObjectType:"compost",ObjectID:"lot-1",CollectedBy:"env-1",CollectedAt:now.Add(-time.Hour),Temperature:20,Seal:"seal-1"}}
func number(value float64)*float64{return &value}
func TestEvaluatePassesCurrentMeasurements(t *testing.T){now:=time.Now();s:=sample(now);measurements:=[]Measurement{{ID:"m1",SampleID:s.ID,Metric:"moisture",Value:.25,Unit:"ratio",Method:"oven",MeasuredAt:now,LabID:"lab"},{ID:"m2",SampleID:s.ID,Metric:"ph",Value:7.2,Unit:"ph",Method:"probe",MeasuredAt:now,LabID:"lab"}};specs:=[]Specification{{Metric:"moisture",Unit:"ratio",Maximum:number(.3),RequiredMethod:"oven",MaxAge:time.Hour},{Metric:"ph",Unit:"ph",Minimum:number(6.5),Maximum:number(8),RequiredMethod:"probe"}};decision,err:=Evaluate(s,measurements,specs,now);if err!=nil||!decision.Passed||len(decision.Failures)!=0{t.Fatalf("decision=%+v err=%v",decision,err)}}
func TestEvaluateReportsMissingExpiredAndOutOfRange(t *testing.T){now:=time.Now();s:=sample(now);measurements:=[]Measurement{{ID:"m1",SampleID:s.ID,Metric:"moisture",Value:.5,Unit:"ratio",Method:"oven",MeasuredAt:now.Add(-2*time.Hour),LabID:"lab"}};specs:=[]Specification{{Metric:"moisture",Unit:"ratio",Maximum:number(.3),MaxAge:time.Hour},{Metric:"ph",Unit:"ph"}};decision,err:=Evaluate(s,measurements,specs,now);if err!=nil||decision.Passed||len(decision.Failures)!=2{t.Fatalf("decision=%+v err=%v",decision,err)};if decision.Failures[0].Metric!="moisture"||decision.Failures[0].Code!="expired"{t.Fatal(decision.Failures)}}
func TestVerifyChain(t *testing.T){now:=time.Now();s:=sample(now);entries:=[]ChainEntry{{Sequence:1,SampleID:s.ID,FromActor:"a",ToActor:"b",Location:"barn",SealBefore:s.Seal,SealAfter:"seal-2",TransferredAt:now},{Sequence:2,SampleID:s.ID,FromActor:"b",ToActor:"c",Location:"lab",SealBefore:"seal-2",SealAfter:"seal-3",TransferredAt:now.Add(time.Hour)}};if err:=VerifyChain(s,entries);err!=nil{t.Fatal(err)};entries[1].SealBefore="wrong";if !errors.Is(VerifyChain(s,entries),domain.ErrConflict){t.Fatal("broken seal accepted")}}
func TestMergeMeasurementsUsesNewestAndRejectsIdentityReuse(t *testing.T){now:=time.Now();old:=Measurement{ID:"m",SampleID:"s",Metric:"ph",Value:7,MeasuredAt:now};newer:=old;newer.Value=8;newer.MeasuredAt=now.Add(time.Hour);out,err:=MergeMeasurements([]Measurement{old},[]Measurement{newer});if err!=nil||len(out)!=1||out[0].Value!=8{t.Fatalf("out=%+v err=%v",out,err)};newer.Metric="moisture";if _,err=MergeMeasurements([]Measurement{old},[]Measurement{newer});!errors.Is(err,domain.ErrConflict){t.Fatalf("err=%v",err)}}
